"""Reports router: markdown and PDF export."""

from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import User
from app.db.session import get_db
from app.deps import get_current_user
from app.runs.service import get_run

router = APIRouter()


def _generate_markdown_report(run) -> str:
    """Generate a markdown report from a completed run result.

    Handles both the rich result from the real stocksage engine
    (with decision, analysis, debate sections) and the simple
    stub result.
    """
    result = run.result or {}

    lines = [
        "# StockSage Analysis Report",
        "",
        f"**Symbol:** {run.symbol}",
        f"**Stock:** {run.stock_name or 'N/A'}",
        f"**Status:** {run.status}",
        f"**Created:** {run.created_at}",
        "",
    ]

    if run.status == "failed":
        lines.append("## Error")
        lines.append("")
        lines.append(run.error_message or "Unknown error")
        lines.append("")
        lines.append("---")
        lines.append("*Generated by StockSage*")
        return "\n".join(lines)

    if run.status != "completed" or not result:
        lines.append("---")
        lines.append("*Generated by StockSage*")
        return "\n".join(lines)

    # Check if this is a rich result from the real engine
    decision = result.get("decision", {})
    has_real_decision = isinstance(decision, dict) and "recommendation" in decision

    if has_real_decision:
        # Rich report from real engine
        lines.append("## Decision")
        lines.append("")
        lines.append(f"**Recommendation:** {decision.get('recommendation', 'N/A')}")
        lines.append(f"**Confidence:** {decision.get('confidence', 'N/A')}")
        lines.append("")

        if core_logic := decision.get("core_logic"):
            lines.append(f"**Core Logic:** {core_logic}")
            lines.append("")

        # Dimension scores
        if scores := decision.get("dimension_scores"):
            lines.append("### Dimension Scores")
            lines.append("")
            lines.append("| Dimension | Score |")
            lines.append("|-----------|-------|")
            for dim, score in scores.items():
                lines.append(f"| {dim} | {score} |")
            lines.append("")
            if ws := decision.get("weighted_score"):
                lines.append(f"**Weighted Score:** {ws}")
                lines.append("")

        # Bull factors
        if bull := decision.get("bull_factors"):
            lines.append("### Bull Factors")
            lines.append("")
            for f in bull:
                lines.append(f"- {f}")
            lines.append("")

        # Bear factors
        if bear := decision.get("bear_factors"):
            lines.append("### Bear Factors")
            lines.append("")
            for f in bear:
                lines.append(f"- {f}")
            lines.append("")

        # Risk warning
        if risk := decision.get("risk_warning"):
            lines.append(f"**Risk Warning:** {risk}")
            lines.append("")

        # Action strategy
        if strategy := decision.get("action_strategy"):
            lines.append(f"**Action Strategy:** {strategy}")
            lines.append("")

        # Key watch points
        if watch := decision.get("key_watch_points"):
            lines.append("### Key Watch Points")
            lines.append("")
            for w in watch:
                lines.append(f"- {w}")
            lines.append("")

        # Dimension summaries
        if dims := decision.get("dimension_summary"):
            lines.append("### Dimension Analysis Summary")
            lines.append("")
            for dim, summary in dims.items():
                lines.append(f"**{dim}:** {summary}")
                lines.append("")

        # Blind spot assessment
        if blind_spots := decision.get("blind_spot_assessment"):
            lines.append("### Blind Spot Assessment")
            lines.append("")
            for bs in blind_spots:
                addressed = "Addressed" if bs.get("addressed_in_debate") else "Not addressed"
                evidence = "Evidence found" if bs.get("evidence_found") else "No evidence"
                lines.append(f"- **{bs.get('blind_spot', '')}** [{addressed} | {evidence}]")
                if bs.get("evidence_summary"):
                    lines.append(f"  - Evidence: {bs['evidence_summary']}")
                if bs.get("conclusion"):
                    lines.append(f"  - Conclusion: {bs['conclusion']}")
            lines.append("")

        # Analysis section (individual analyst results)
        analysis = result.get("analysis", {})
        if analysis:
            lines.append("## Individual Analyses")
            lines.append("")
            for analyst_name, analyst_result in analysis.items():
                title = analyst_name.replace("_", " ").title()
                lines.append(f"### {title}")
                lines.append("")
                if isinstance(analyst_result, dict):
                    summary = analyst_result.get("summary", "")
                    if summary:
                        lines.append(summary)
                        lines.append("")
                    for k, v in analyst_result.items():
                        if k == "summary":
                            continue
                        if isinstance(v, (list, dict)):
                            import json
                            lines.append(f"**{k}:** {json.dumps(v, ensure_ascii=False, indent=2)}")
                        else:
                            lines.append(f"**{k}:** {v}")
                    lines.append("")
                else:
                    lines.append(str(analyst_result))
                    lines.append("")

        # Errors
        errors = result.get("errors", [])
        if errors:
            lines.append("## Warnings")
            lines.append("")
            for err in errors:
                lines.append(f"- {err}")
            lines.append("")

    else:
        # Simple stub result
        lines.append("## Summary")
        lines.append("")
        summary = result.get("summary", "No summary available")
        lines.append(summary)
        lines.append("")

        for key, value in result.items():
            if key in ("symbol", "stock_name", "status", "summary",
                        "meta", "recommendation", "confidence"):
                continue
            lines.append(f"## {key.replace('_', ' ').title()}")
            lines.append("")
            if isinstance(value, dict):
                for k, v in value.items():
                    lines.append(f"- **{k}:** {v}")
            elif isinstance(value, list):
                for item in value:
                    lines.append(f"- {item}")
            else:
                lines.append(str(value))
            lines.append("")

    lines.append("---")
    lines.append("*Generated by StockSage*")

    return "\n".join(lines)


@router.get("/{run_id}/markdown")
async def get_markdown_report(
    run_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    run = await get_run(db, run_id)
    if run is None or run.owner_id != current_user.id:
        raise HTTPException(status_code=404, detail="Run not found")
    if run.status not in ("completed", "failed"):
        raise HTTPException(status_code=409, detail="Run not yet finished")

    md = _generate_markdown_report(run)
    return PlainTextResponse(content=md, media_type="text/markdown")


@router.get("/{run_id}/pdf")
async def get_pdf_report(
    run_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """PDF generation placeholder.

    Full PDF generation requires the core stocksage report module.
    For now, returns the markdown as a downloadable text file.
    """
    run = await get_run(db, run_id)
    if run is None or run.owner_id != current_user.id:
        raise HTTPException(status_code=404, detail="Run not found")
    if run.status not in ("completed", "failed"):
        raise HTTPException(status_code=409, detail="Run not yet finished")

    md = _generate_markdown_report(run)
    return PlainTextResponse(
        content=md,
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="report_{run_id}.md"'},
    )
